### ISSUE TITLE
Question on latency

### ISSUE THREAD

**Issue by Fubaxiusz** [trzy/PixArt#2]
Hello, thanks for your great work.
Do you know the latach of Pixar sensor? Is it noticeable, does it feel like the output is dragged a bit or is it instant, like Mouse? Thanks.

**Comment by trzy** [comment]
I haven’t tried to measure. And it also depends on what you mean by latency. Photon to reception on the PC? Well that’s going to depend on the USB stacks of the microcontroller and PC. Photon to packet readout on the microcontroller directly connected to the chip? That should be a lot faster. The data sheet may have this information (don’t know it offhand) and my guess is it is probably around one frame of latency, but I don’t know for sure.
